#!/bin/bash

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -eo pipefail

ABBREV='<ABBREV>'

echo '###########################'
echo "BEGIN $ABBREV-user1 actions"
echo '###########################'

echo '+++++++++++++++++++++'
echo 'BEGIN: installing NVM'
echo '+++++++++++++++++++++'

echo '-------------------------------------------------------------------'
echo "git clone https://github.com/creationix/nvm.git /home/`whoami`/.nvm"
git clone https://github.com/creationix/nvm.git /home/`whoami`/.nvm

echo '-----------------------------------------'
echo "cd /home/`whoami`/.nvm && bash install.sh"
cd /home/`whoami`/.nvm && bash install.sh

echo '----'
echo 'wait'
wait

echo '++++++++++++++++++++++++'
echo 'FINISHED: installing NVM'
echo '++++++++++++++++++++++++'

echo '##############################'
echo "FINISHED $ABBREV-user1 actions"
echo '##############################'
